import "./globals.css";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className="font-poppins bg-[#F5F5F5]">
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
